INSERT INTO tbl_cards (hp, name, typeID, stageID, info, attack, damage, weak, ressis, retreat, cardNumberInCollection, collectionID)
VALUES
(50, 'Magikarp', 1, 1, 'A weak and pathetic fish Pokémon.', 'Splash', '0', 'Electric', 'Fire', 1, 129, 1),
(130, 'Gyarados', 1, 3, 'Evolves from Magikarp. A ferocious sea beast.', 'Hyper Beam', '100', 'Electric', 'Fire', 3, 130, 1),
(70, 'Snorlax', 5, 1, 'A sleeping giant that is hard to wake.', 'Body Slam', '50', 'Fighting', 'Psychic', 4, 143, 2),
(90, 'Cubone', 5, 1, 'Wears the skull of its deceased mother.', 'Bone Club', '30', 'Water', 'Electric', 1, 104, 3),
(110, 'Marowak', 5, 2, 'Evolves from Cubone. Uses its bone as a weapon.', 'Bonemerang', '50', 'Water', 'Electric', 2, 105, 3),
(60, 'Nidoran♀', 3, 1, 'A small poisonous Pokémon.', 'Scratch', '20', 'Psychic', 'None', 1, 29, 2),
(80, 'Nidorina', 3, 2, 'Evolves from Nidoran♀.', 'Bite', '30', 'Psychic', 'None', 1, 30, 2),
(90, 'Nidoqueen', 3, 3, 'Evolves from Nidorina. A defensive powerhouse.', 'Earthquake', '90', 'Psychic', 'None', 3, 31, 2),
(60, 'Nidoran♂', 3, 1, 'A small poisonous Pokémon.', 'Peck', '20', 'Psychic', 'None', 1, 32, 2),
(80, 'Nidorino', 3, 2, 'Evolves from Nidoran♂.', 'Horn Attack', '30', 'Psychic', 'None', 1, 33, 2),
(90, 'Nidoking', 3, 3, 'Evolves from Nidorino. A powerhouse with sharp claws.', 'Megahorn', '90', 'Psychic', 'None', 3, 34, 2),
(70, 'Meowth', 5, 1, 'Loves shiny objects.', 'Scratch', '20', 'Fighting', 'None', 0, 52, 1),
(80, 'Persian', 5, 2, 'Evolves from Meowth. A sleek and agile cat Pokémon.', 'Slash', '50', 'Fighting', 'None', 1, 53, 1),
(50, 'Pidgey', 5, 1, 'A tiny bird Pokémon that is very common.', 'Tackle', '10', 'Electric', 'Grass', 0, 16, 1),
(70, 'Pidgeotto', 5, 2, 'Evolves from Pidgey.', 'Wing Attack', '20', 'Electric', 'Grass', 1, 17, 1),
(120, 'Pidgeot', 5, 3, 'Evolves from Pidgeotto. Known for its speed.', 'Hurricane', '90', 'Electric', 'Grass', 2, 18, 1),
(90, 'Lapras', 1, 1, 'A gentle creature that ferries people across water.', 'Ice Beam', '70', 'Electric', 'Fire', 3, 131, 1),
(70, 'Abra', 5, 1, 'A psychic Pokémon that sleeps to build energy.', 'Teleport', '0', 'Psychic', 'None', 0, 63, 3),
(90, 'Kadabra', 5, 2, 'Evolves from Abra. Known for its psychic powers.', 'Psybeam', '50', 'Psychic', 'None', 1, 64, 3),
(110, 'Alakazam', 5, 3, 'Evolves from Kadabra. Extremely intelligent.', 'Psychic', '90', 'Psychic', 'None', 2, 65, 3),
(60, 'Slowpoke', 5, 1, 'A sluggish Pokémon.', 'Water Gun', '20', 'Electric', 'Fire', 1, 79, 2),
(80, 'Slowbro', 1, 2, 'Evolves from Slowpoke. A laid-back Pokémon.', 'Surf', '40', 'Electric', 'Fire', 2, 80, 2),
(50, 'Diglett', 5, 1, 'Lives underground and can dig quickly.', 'Scratch', '10', 'Water', 'Electric', 0, 50, 2),
(80, 'Dugtrio', 5, 2, 'Evolves from Diglett. A trio of digging Pokémon.', 'Earthquake', '70', 'Water', 'Electric', 2, 51, 2),
(70, 'Ekans', 5, 1, 'A snake Pokémon that coils around its prey.', 'Wrap', '20', 'Ground', 'None', 1, 23, 1),
(90, 'Arbok', 5, 2, 'Evolves from Ekans. Known for its intimidating pattern.', 'Poison Fang', '40', 'Ground', 'None', 1, 24, 1),
(50, 'Poliwag', 1, 1, 'A water Pokémon with a spiral pattern on its belly.', 'Bubble', '10', 'Electric', 'Fire', 0, 60, 1),
(80, 'Poliwhirl', 1, 2, 'Evolves from Poliwag.', 'Water Gun', '30', 'Electric', 'Fire', 1, 61, 1),
(100, 'Poliwrath', 1, 3, 'Evolves from Poliwhirl. Combines water and fighting skills.', 'Hydro Pump', '90', 'Electric', 'Fire', 2, 62, 1),
(70, 'Jynx', 5, 1, 'Known for its humanlike shape and icy powers.', 'Ice Punch', '30', 'Steel', 'Fire', 2, 124, 3);