INSERT INTO tbl_cards (hp, name, typeID, stageID, info, attack, damage, weak, ressis, retreat, cardNumberInCollection, collectionID)
VALUES
(60, 'Rattata', 5, 1, 'A small and quick rodent Pokémon.', 'Tackle', '10', 'Fighting', 'None', 1, 19, 1),
(80, 'Raticate', 5, 2, 'Evolves from Rattata. Known for its large fangs.', 'Hyper Fang', '50', 'Fighting', 'None', 1, 20, 1),
(50, 'Caterpie', 3, 1, 'A worm Pokémon that eats leaves.', 'String Shot', '10', 'Fire', 'Grass', 1, 10, 1),
(60, 'Metapod', 3, 2, 'Evolves from Caterpie. Known for its hard shell.', 'Harden', '0', 'Fire', 'Grass', 2, 11, 1),
(70, 'Venonat', 3, 1, 'Has big eyes for scouting its surroundings.', 'Confusion', '20', 'Fire', 'Psychic', 1, 48, 1),
(100, 'Venomoth', 3, 3, 'Evolves from Venonat. Known for its powdery scales.', 'Psybeam', '50', 'Fire', 'Psychic', 1, 49, 1),
(60, 'Paras', 3, 1, 'Mushroom Pokémon that thrives in damp places.', 'Scratch', '20', 'Fire', 'None', 1, 46, 2),
(70, 'Parasect', 3, 2, 'Evolves from Paras. It controls its host with fungi.', 'Spore', '40', 'Fire', 'None', 2, 47, 2),
(40, 'Weedle', 3, 1, 'A bug Pokémon with a venomous stinger.', 'Poison Sting', '10', 'Fire', 'Grass', 1, 13, 1),
(50, 'Kakuna', 3, 2, 'Evolves from Weedle. Its shell is very hard.', 'Harden', '0', 'Fire', 'Grass', 2, 14, 1),
(120, 'Beedrill', 3, 3, 'Evolves from Kakuna. Known for its sharp stingers.', 'Twineedle', '60', 'Fire', 'Grass', 1, 15, 1),
(80, 'Seel', 1, 1, 'A sea lion Pokémon that loves icy seas.', 'Aurora Beam', '30', 'Electric', 'Fire', 2, 86, 3),
(120, 'Dewgong', 1, 3, 'Evolves from Seel. It swims swiftly in icy waters.', 'Ice Beam', '70', 'Electric', 'Fire', 3, 87, 3),
(70, 'Krabby', 1, 1, 'A crab Pokémon that waves its pincers.', 'Vice Grip', '20', 'Electric', 'None', 1, 98, 3),
(110, 'Kingler', 1, 2, 'Evolves from Krabby. Its pincers can crush anything.', 'Crabhammer', '50', 'Electric', 'None', 2, 99, 3),
(100, 'Electabuzz', 4, 1, 'A Pokémon that generates electricity.', 'Thunder Punch', '60', 'Ground', 'Steel', 1, 125, 3),
(50, 'Magnemite', 4, 1, 'A Pokémon that appears to be made of magnets.', 'Thunder Shock', '30', 'Ground', 'Steel', 0, 81, 1),
(80, 'Magneton', 4, 3, 'Evolves from Magnemite. Known for its magnetic field.', 'Zap Cannon', '70', 'Ground', 'Steel', 2, 82, 1),
(50, 'Horsea', 1, 1, 'A water Pokémon that swims gracefully.', 'Bubble', '10', 'Electric', 'Fire', 0, 116, 2),
(80, 'Seadra', 1, 2, 'Evolves from Horsea. Its venom can paralyze opponents.', 'Water Gun', '30', 'Electric', 'Fire', 1, 117, 2),
(70, 'Sandshrew', 5, 1, 'A desert-dwelling Pokémon with a tough hide.', 'Scratch', '10', 'Water', 'Electric', 1, 27, 2),
(100, 'Sandslash', 5, 2, 'Evolves from Sandshrew. Known for its sharp claws.', 'Slash', '40', 'Water', 'Electric', 2, 28, 2),
(90, 'Hitmonlee', 5, 1, 'A fighting Pokémon with legs of steel.', 'High Jump Kick', '70', 'Psychic', 'None', 2, 106, 3),
(90, 'Hitmonchan', 5, 1, 'A fighting Pokémon that throws fast punches.', 'Fire Punch', '60', 'Psychic', 'None', 1, 107, 3),
(60, 'Lickitung', 5, 1, 'Its long tongue is highly versatile.', 'Lick', '20', 'Fighting', 'None', 2, 108, 2),
(60, 'Voltorb', 4, 1, 'A Pokémon that resembles a Poké Ball.', 'Spark', '20', 'Ground', 'Steel', 0, 100, 1),
(100, 'Electrode', 4, 2, 'Evolves from Voltorb. Known for exploding unexpectedly.', 'Explosion', '120', 'Ground', 'Steel', 1, 101, 1),
(70, 'Doduo', 5, 1, 'A two-headed bird Pokémon that is fast on its feet.', 'Peck', '10', 'Electric', 'Grass', 1, 84, 1),
(90, 'Dodrio', 5, 2, 'Evolves from Doduo. Its three heads can sense danger.', 'Tri Attack', '40', 'Electric', 'Grass', 2, 85, 1);